"""update tool model for webhook tools

Revision ID: 29f4a4f0687b
Revises: 49847e14949c
Create Date: 2026-05-22 21:17:08.678040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29f4a4f0687b'
down_revision: Union[str, Sequence[str], None] = '49847e14949c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('input_schema', sa.JSON(), nullable=False, server_default=sa.text("'{}'::json")))
    op.add_column('tools', sa.Column('output_schema', sa.JSON(), nullable=True))
    op.add_column('tools', sa.Column('example_request', sa.JSON(), nullable=True))
    op.add_column('tools', sa.Column('example_response', sa.JSON(), nullable=True))
    op.add_column('tools', sa.Column('webhook_url', sa.Text(), nullable=False, server_default=sa.text("'{}'::json")))
    op.create_index(op.f('ix_tools_id'), 'tools', ['id'], unique=False)
    op.drop_column('tools', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_tools_id'), table_name='tools')
    op.drop_column('tools', 'webhook_url')
    op.drop_column('tools', 'example_response')
    op.drop_column('tools', 'example_request')
    op.drop_column('tools', 'output_schema')
    op.drop_column('tools', 'validation_rules')
    op.drop_column('tools', 'input_schema')
    # ### end Alembic commands ###
