"""add workflow_id to agent tasks

Revision ID: 38135072bfa3
Revises: 51cfaa2178c8
Create Date: 2026-05-24 02:49:31.987057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38135072bfa3'
down_revision: Union[str, Sequence[str], None] = '51cfaa2178c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_tasks', sa.Column('workflow_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'agent_tasks', 'agent_workflows', ['workflow_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agent_tasks', type_='foreignkey')
    op.drop_column('agent_tasks', 'workflow_id')
    # ### end Alembic commands ###
