"""add webhook tools

Revision ID: 49847e14949c
Revises: 8ab0f77fcde6
Create Date: 2026-05-22 18:44:10.298665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49847e14949c'
down_revision: Union[str, Sequence[str], None] = '8ab0f77fcde6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('is_webhook', sa.Boolean(), nullable=True))
    op.add_column('tools', sa.Column('webhook_method', sa.String(), nullable=True))
    op.add_column('tools', sa.Column('webhook_headers', sa.JSON(), nullable=True))
    op.add_column('tools', sa.Column('webhook_timeout_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tools', 'webhook_timeout_seconds')
    op.drop_column('tools', 'webhook_headers')
    op.drop_column('tools', 'webhook_method')
    op.drop_column('tools', 'is_webhook')
    # ### end Alembic commands ###
