"""update tool model for webhook tools

Revision ID: 51cfaa2178c8
Revises: 29f4a4f0687b
Create Date: 2026-05-22 21:36:24.653898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51cfaa2178c8'
down_revision: Union[str, Sequence[str], None] = '29f4a4f0687b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('validation_rules', sa.JSON(), nullable=True))
    op.alter_column('tools', 'webhook_url',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tools', 'webhook_url',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.drop_column('tools', 'validation_rules')
    # ### end Alembic commands ###
