"""add workflows

Revision ID: 8ab0f77fcde6
Revises: 51e19a362dc2
Create Date: 2026-05-16 05:54:14.708218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ab0f77fcde6'
down_revision: Union[str, Sequence[str], None] = '51e19a362dc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('coordinator_agent_id', sa.Integer(), nullable=False),
    sa.Column('shared_context', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_workflows_id'), 'agent_workflows', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_workflows_id'), table_name='agent_workflows')
    op.drop_table('agent_workflows')
    # ### end Alembic commands ###
